CREATE TABLE TBLCLIENTE
(
  ID          NUMBER(6) NOT NULL,
  NOME        VARCHAR2(100),
  CEP         VARCHAR2(9),  
  LOGRADOURO  VARCHAR2(100),
  COMPLEMENTO VARCHAR2(50),  
  BAIRRO      VARCHAR2(50),
  CIDADE      VARCHAR2(20),
  UF          VARCHAR2(2),
  CODIBGE     VARCHAR2(10)
);

CREATE TABLE TBLPRODUTO
(
  ID        NUMBER(6) NOT NULL,
  DESCRICAO VARCHAR2(60)
);

CREATE TABLE TBLPEDIDO
(
  ID         NUMBER(6) NOT NULL,
  REFERENCIA VARCHAR2(60),
  NUMPEDIDO  NUMBER(6),
  DTEMISSAO  DATE,
  IDCLIENTE  NUMBER(6),
  TIPOOPER   VARCHAR2(1),
  VLTOTAL    NUMBER(16,3)
);

CREATE TABLE TBLITEM
(
  IDPEDIDO   NUMBER(6) NOT NULL,
  IDPRODUTO  NUMBER(6),
  QUANTIDADE NUMBER(6),
  VLUNITARIO NUMBER(16,3),
  VLTOTAL    NUMBER(16,3)
);